### PR TITLE
[BULK UPDATE] DocuTune - Rebranding links

### PR DESCRIPTION
**Pull request by alexbuckgit**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

**Global effort for the Microsoft Learn platform rebrand**

The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.

Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.

This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.

CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[060b6a5](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/commits/060b6a5ad4f1cbddf02cc5ca9481db78fd8e4c64)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SP-Framework/sp-http/aadhttpclientfactory.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-http/aadhttpclientfactory.yml) | :warning:Warning | | [Details](#user-content-7cce6b18c3ddf03d338fc2eddc4b703c-e4538401)
[SP-Framework/sp-http/msgraphclientfactory.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-http/msgraphclientfactory.yml) | :warning:Warning | | [Details](#user-content-0d8a7b1d2f8915147d7ea20527ac18a0-e4538401)
[SP-Framework/sp-webpart-base/imicrosoftteams.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-webpart-base/imicrosoftteams.yml) | :warning:Warning | | [Details](#user-content-bd1acd3fbc2d61a96df3029d7d44b5d3-e4538401)
[SP-Framework/sp-webpart-base/webpartcontext.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-webpart-base/webpartcontext.yml) | :warning:Warning | | [Details](#user-content-04d91d95243526e8ea537a3c74f13170-e4538401)
[SP-Framework/overview/sharepoint.md](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/overview/sharepoint.md) | :white_check_mark:Succeeded | |
[SP-Framework/sp-webpart-base/isdks.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-webpart-base/isdks.yml) | :white_check_mark:Succeeded | |

<a id="7cce6b18c3ddf03d338fc2eddc4b703c-e4538401"></a>
### [SP-Framework/sp-http/aadhttpclientfactory.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-http/aadhttpclientfactory.yml)
 - **Line 27, Column 77**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/sp-http!default:class'.`````
 - **Line 48, Column 26**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/sp-http!default:class'.`````

<a id="0d8a7b1d2f8915147d7ea20527ac18a0-e4538401"></a>
### [SP-Framework/sp-http/msgraphclientfactory.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-http/msgraphclientfactory.yml)
 - **Line 27, Column 77**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/sp-http!default:class'.`````
 - **Line 48, Column 26**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/sp-http!default:class'.`````

<a id="bd1acd3fbc2d61a96df3029d7d44b5d3-e4538401"></a>
### [SP-Framework/sp-webpart-base/imicrosoftteams.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-webpart-base/imicrosoftteams.yml)
 - **Line 25, Column 30**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/teams-js!Context:interface'.`````

<a id="04d91d95243526e8ea537a3c74f13170-e4538401"></a>
### [SP-Framework/sp-webpart-base/webpartcontext.yml](https://github.com/alexbuckgit/sp-dev-docs-ref-typescript/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220920-191839-3478570/SP-Framework/sp-webpart-base/webpartcontext.yml)
 - **Line 68, Column 15**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/sp-webpart-base!default:interface'.`````
 - **Line 83, Column 10**: **[Warning: xref-not-found]** `````Cross reference not found: '@microsoft/sp-webpart-base!default:class'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/f0bbeece-42a1-bc25-c6a0-ab671d868033/202209201918463882-38/BuildReport?accessString=6abe663b6202f932e2850d84c28ac92f31244e9c9cc5141f3c1d3e3e3f72455b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/f0bbeece-42a1-bc25-c6a0-ab671d868033?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by annmariehitchcock** [comment]
#docutune-ready

**Comment by alexbuckgit** [comment]
Hi @VesaJuvonen -

Please merge, thanks!

#docutune-request-approval

**Comment by alexbuckgit** [comment]
#docutune-stuck

**Comment by alexbuckgit** [comment]
@andrewconnell - Please merge, thanks!

**Comment by VesaJuvonen** [comment]
Sorry for the delay - better late than never... :-)

**Pull request merged**
